---
title: "5513 assignment 2"
author: "DIYAO CHEN"
date: "2020/4/24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction
My research question is What Nintendo future strategies should be? 
For the data wrangling, base on global sales, I chose the top 1000 selling games in the world as my data set.


#loading library
```{r , message = FALSE}
library(tidyverse)
library(readr)
library(kableExtra)
library(ggplot2)
library(lubridate)
library(gridExtra)
library(rmdformats)
library(readxl)
```


```{r , message = FALSE, echo=FALSE}
dat<- read_excel("D:\\Rstudioxuexi\\video_games_sales.xlsx")
head(dat)
```


# histocial data analysis
```{r historical data, message = FALSE, echo=FALSE}
dat2 <- dat %>% dplyr::select(Publisher,Global_Sales)

head(dat2,n=5)

```

```{r analysis Nintendo sell rank ,  message=FALSE, warning=FALSE}
dat3<- dat2 %>%
  dplyr::select(Publisher) %>%
  group_by(Publisher) %>%
 mutate(Cases = n()) %>%
  unique() %>%
  arrange(-Cases)
print(dat3)

```

```{r creat a table  ,  message=FALSE, warning=FALSE}

kable(caption = "Nintendo's percentage of the world's top 1000 best-selling games",dat3)%>%
  kable_styling(bootstrap_options = c("striped","hover"))

Nintendo percentage <- 228/1000
```